// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bindings is the v3 service exposed to the frontend. wails3 generate
 * bindings reads its method set and writes typed wrappers into
 * frontend/bindings/. The struct holds the config store and the App so
 * methods can fire custom events from any goroutine.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function AddRepo(name, url) {
    return $Call.ByID(3238270672, name, url);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function AddScript(name) {
    return $Call.ByID(876666543, name);
}

/**
 * AddWorkspace creates a workspace and streams progress as custom Wails
 * events. The pipe + scanner mirrors what the SSE handler does for HTTP:
 * each line becomes one "workspace:progress" event; the outcome is
 * "workspace:done" or "workspace:error".
 * @param {string} name
 * @param {string[]} packages
 * @returns {$CancellablePromise<void>}
 */
export function AddWorkspace(name, packages) {
    return $Call.ByID(1283457793, name, packages);
}

/**
 * AttachCommand returns the shell command to attach to (or launch) the
 * workspace's tmux session.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function AttachCommand(name) {
    return $Call.ByID(2979582093, name);
}

/**
 * CdWorkspace returns the workspace's on-disk path so JS can copy
 * `cd <path>` to the clipboard.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CdWorkspace(name) {
    return $Call.ByID(549123331, name);
}

/**
 * @param {string} dst
 * @param {string[]} packages
 * @returns {$CancellablePromise<void>}
 */
export function CloneWorkspace(dst, packages) {
    return $Call.ByID(2233424899, dst, packages);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateWorkspaceOnDisk(name) {
    return $Call.ByID(1697980134, name);
}

/**
 * @param {string} name
 * @param {string[]} packages
 * @returns {$CancellablePromise<void>}
 */
export function EditWorkspace(name, packages) {
    return $Call.ByID(3568626706, name, packages);
}

/**
 * ExplorePath returns the workspace path so JS can open it via
 * app.Browser.OpenURL("file://"+path) in v3.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExplorePath(name) {
    return $Call.ByID(1232296283, name);
}

/**
 * @returns {$CancellablePromise<$models.ConfigDTO>}
 */
export function GetConfig() {
    return $Call.ByID(2417901941).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListMuxSessions() {
    return $Call.ByID(1638008752).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: $models.RepoDTO }>}
 */
export function ListRepos() {
    return $Call.ByID(3114278478).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListScripts() {
    return $Call.ByID(4015175911).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: $models.WorkspaceDTO }>}
 */
export function ListWorkspaces() {
    return $Call.ByID(3686458755).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.OpenCommandDTO>}
 */
export function OpenCommand(name) {
    return $Call.ByID(586450886, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * OpenEditor spawns the configured editor against the workspace and
 * returns immediately. The desktop app calls this on workspace click so
 * the user gets a GUI launch instead of the legacy clipboard-copy flow.
 * Use OpenCommand if the caller wants the invocation as data.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function OpenEditor(name) {
    return $Call.ByID(2318643228, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMuxSession(name) {
    return $Call.ByID(3196518839, name);
}

/**
 * @param {string[]} names
 * @returns {$CancellablePromise<void>}
 */
export function RemoveRepos(names) {
    return $Call.ByID(3120735266, names);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveScript(name) {
    return $Call.ByID(791188114, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWorkspace(name) {
    return $Call.ByID(2259163742, name);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ScriptsDir() {
    return $Call.ByID(2010521178);
}

/**
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetEditor(value) {
    return $Call.ByID(1697442118, value);
}

/**
 * @param {string} repo
 * @param {string[]} scriptsList
 * @returns {$CancellablePromise<void>}
 */
export function SetRepoPostInstall(repo, scriptsList) {
    return $Call.ByID(2851266120, repo, scriptsList);
}

/**
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetRoot(value) {
    return $Call.ByID(2376132863, value);
}

/**
 * @param {string} name
 * @param {string[]} scriptsList
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkspacePostInstall(name, scriptsList) {
    return $Call.ByID(1356373713, name, scriptsList);
}

// Private type creation functions
const $$createType0 = $models.ConfigDTO.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.RepoDTO.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $models.WorkspaceDTO.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = $models.OpenCommandDTO.createFrom;
