// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bindings is the v3 service exposed to the frontend. wails3 generate
 * bindings reads its method set and writes typed wrappers into
 * frontend/bindings/. The struct holds the config store and the App so
 * methods can fire custom events from any goroutine.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function AddEditor(name, command) {
    return $Call.ByID(1705413485, name, command);
}

/**
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function AddRepo(name, url) {
    return $Call.ByID(3238270672, name, url);
}

/**
 * @param {string} name
 * @param {string} scope
 * @returns {$CancellablePromise<void>}
 */
export function AddScript(name, scope) {
    return $Call.ByID(876666543, name, scope);
}

/**
 * AddWorkspace creates a workspace and streams progress as custom Wails
 * events. The pipe + scanner mirrors what the SSE handler does for HTTP:
 * each line becomes one "workspace:progress" event; the outcome is
 * "workspace:done" or "workspace:error". postInstall optionally attaches
 * workspace-scoped scripts to the new workspace before the build runs.
 * @param {string} name
 * @param {string[]} packages
 * @param {string[]} postInstall
 * @returns {$CancellablePromise<void>}
 */
export function AddWorkspace(name, packages, postInstall) {
    return $Call.ByID(1283457793, name, packages, postInstall);
}

/**
 * AttachCommand returns the shell command to attach to (or launch) the
 * workspace's tmux session.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function AttachCommand(name) {
    return $Call.ByID(2979582093, name);
}

/**
 * CdWorkspace returns the workspace's on-disk path so JS can copy
 * `cd <path>` to the clipboard.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CdWorkspace(name) {
    return $Call.ByID(549123331, name);
}

/**
 * @param {string} dst
 * @param {string[]} packages
 * @returns {$CancellablePromise<void>}
 */
export function CloneWorkspace(dst, packages) {
    return $Call.ByID(2233424899, dst, packages);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateWorkspaceOnDisk(name) {
    return $Call.ByID(1697980134, name);
}

/**
 * @param {string} name
 * @param {string[]} packages
 * @returns {$CancellablePromise<void>}
 */
export function EditWorkspace(name, packages) {
    return $Call.ByID(3568626706, name, packages);
}

/**
 * ExplorePath returns the workspace path so JS can open it via
 * app.Browser.OpenURL("file://"+path) in v3.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExplorePath(name) {
    return $Call.ByID(1232296283, name);
}

/**
 * @returns {$CancellablePromise<$models.ConfigDTO>}
 */
export function GetConfig() {
    return $Call.ByID(2417901941).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * InspectOrphan resolves an orphan directory and detects what repos
 * live inside it via go-git, plus surfaces the preserved post-install
 * scripts the restore will rebind.
 * @param {string} name
 * @returns {$CancellablePromise<$models.OrphanInspectionDTO>}
 */
export function InspectOrphan(name) {
    return $Call.ByID(46565281, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListMuxSessions() {
    return $Call.ByID(1638008752).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListOrphanWorkspaces returns directory names under the configured root
 * that are NOT registered workspaces — candidates for cleanup. Settings →
 * Cleanup tab subscribes via callService and pairs this with
 * RemoveOrphanWorkspaces.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListOrphanWorkspaces() {
    return $Call.ByID(4174184541).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: $models.RepoDTO }>}
 */
export function ListRepos() {
    return $Call.ByID(3114278478).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} scope
 * @returns {$CancellablePromise<string[]>}
 */
export function ListScripts(scope) {
    return $Call.ByID(4015175911, scope).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: $models.WorkspaceDTO }>}
 */
export function ListWorkspaces() {
    return $Call.ByID(3686458755).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.OpenCommandDTO>}
 */
export function OpenCommand(name) {
    return $Call.ByID(586450886, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} name
 * @param {string} editor
 * @returns {$CancellablePromise<$models.OpenCommandDTO>}
 */
export function OpenCommandWith(name, editor) {
    return $Call.ByID(414860674, name, editor).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenEditor spawns the configured editor against the workspace and
 * returns immediately. The desktop app calls this on workspace click so
 * the user gets a GUI launch instead of the legacy clipboard-copy flow.
 * Use OpenCommand if the caller wants the invocation as data.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function OpenEditor(name) {
    return $Call.ByID(2318643228, name);
}

/**
 * OpenEditorWith spawns a specific editor (by name) against the workspace.
 * @param {string} name
 * @param {string} editor
 * @returns {$CancellablePromise<void>}
 */
export function OpenEditorWith(name, editor) {
    return $Call.ByID(281778612, name, editor);
}

/**
 * OpenOrphanEditor spawns the default editor against an orphan directory.
 * Mirrors OpenEditor for unregistered dirs surfaced by Settings → Cleanup.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function OpenOrphanEditor(name) {
    return $Call.ByID(1957973650, name);
}

/**
 * OrphanPath returns the absolute path of an orphan directory under the
 * configured workspace root. UI uses it for clipboard copy.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function OrphanPath(name) {
    return $Call.ByID(1286880540, name);
}

/**
 * ReadScript returns the on-disk contents of the named script so the UI
 * can preview it without delegating to an external editor.
 * @param {string} name
 * @param {string} scope
 * @returns {$CancellablePromise<string>}
 */
export function ReadScript(name, scope) {
    return $Call.ByID(3261568490, name, scope);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveEditor(name) {
    return $Call.ByID(2714803216, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMuxSession(name) {
    return $Call.ByID(3196518839, name);
}

/**
 * RemoveOrphanWorkspaces deletes the named directories from the root.
 * The action refuses to delete registered workspaces even if the caller
 * asks, so the UI doesn't need its own guard.
 * @param {string[]} names
 * @returns {$CancellablePromise<void>}
 */
export function RemoveOrphanWorkspaces(names) {
    return $Call.ByID(385411569, names);
}

/**
 * @param {string[]} names
 * @returns {$CancellablePromise<void>}
 */
export function RemoveRepos(names) {
    return $Call.ByID(3120735266, names);
}

/**
 * @param {string} name
 * @param {string} scope
 * @returns {$CancellablePromise<void>}
 */
export function RemoveScript(name, scope) {
    return $Call.ByID(791188114, name, scope);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWorkspace(name) {
    return $Call.ByID(2259163742, name);
}

/**
 * RestoreWorkspace re-registers an orphan directory as a workspace,
 * attaching the given registered repos. Preserved post-install scripts
 * are automatically rebound.
 * @param {string} name
 * @param {string[]} repos
 * @returns {$CancellablePromise<void>}
 */
export function RestoreWorkspace(name, repos) {
    return $Call.ByID(781471698, name, repos);
}

/**
 * RunRepoScript streams a repo-scoped script execution against
 * workspace/repo. workspace is required because the script runs inside
 * the repo's clone path under that workspace's root.
 * @param {string} workspace
 * @param {string} repo
 * @param {string} script
 * @returns {$CancellablePromise<void>}
 */
export function RunRepoScript(workspace, repo, script) {
    return $Call.ByID(4288504941, workspace, repo, script);
}

/**
 * RunWorkspaceScript streams a workspace-scoped script execution against
 * the named workspace's on-disk path. Progress flows through the same
 * custom-event channel as workspace creation so the existing
 * ProgressDrawer subscribes once.
 * @param {string} workspace
 * @param {string} script
 * @returns {$CancellablePromise<void>}
 */
export function RunWorkspaceScript(workspace, script) {
    return $Call.ByID(264979084, workspace, script);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ScriptsDir() {
    return $Call.ByID(2010521178);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultEditor(name) {
    return $Call.ByID(1247010445, name);
}

/**
 * @param {string} repo
 * @param {string[]} scriptsList
 * @returns {$CancellablePromise<void>}
 */
export function SetRepoPostInstall(repo, scriptsList) {
    return $Call.ByID(2851266120, repo, scriptsList);
}

/**
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetRoot(value) {
    return $Call.ByID(2376132863, value);
}

/**
 * @param {string} workspace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkspaceEditor(workspace, name) {
    return $Call.ByID(3620668481, workspace, name);
}

/**
 * @param {string} name
 * @param {string[]} scriptsList
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkspacePostInstall(name, scriptsList) {
    return $Call.ByID(1356373713, name, scriptsList);
}

/**
 * WriteScript replaces the contents of an existing script so the UI can
 * edit a script in place without shelling out to an external editor.
 * @param {string} name
 * @param {string} scope
 * @param {string} contents
 * @returns {$CancellablePromise<void>}
 */
export function WriteScript(name, scope, contents) {
    return $Call.ByID(3999736359, name, scope, contents);
}

// Private type creation functions
const $$createType0 = $models.ConfigDTO.createFrom;
const $$createType1 = $models.OrphanInspectionDTO.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.RepoDTO.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $models.WorkspaceDTO.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = $models.OpenCommandDTO.createFrom;
