// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ConfigDTO mirrors the HTTP layer's configResponse so the same React
 * types compile against either backend.
 */
export class ConfigDTO {
    /**
     * Creates a new ConfigDTO instance.
     * @param {Partial<ConfigDTO>} [$$source = {}] - The source object to create the ConfigDTO.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("editor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editor"] = "";
        }
        if (!("workspaces" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: WorkspaceDTO }}
             */
            this["workspaces"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workspaces" in $$parsedSource) {
            $$parsedSource["workspaces"] = $$createField2_0($$parsedSource["workspaces"]);
        }
        return new ConfigDTO(/** @type {Partial<ConfigDTO>} */($$parsedSource));
    }
}

/**
 * OpenCommandDTO is returned to JS so the UI can display + copy the
 * editor invocation — the app cannot exec an editor that owns a TTY.
 */
export class OpenCommandDTO {
    /**
     * Creates a new OpenCommandDTO instance.
     * @param {Partial<OpenCommandDTO>} [$$source = {}] - The source object to create the OpenCommandDTO.
     */
    constructor($$source = {}) {
        if (!("editor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editor"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenCommandDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenCommandDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenCommandDTO(/** @type {Partial<OpenCommandDTO>} */($$parsedSource));
    }
}

export class RepoDTO {
    /**
     * Creates a new RepoDTO instance.
     * @param {Partial<RepoDTO>} [$$source = {}] - The source object to create the RepoDTO.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["postInstall"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("postInstall" in $$parsedSource) {
            $$parsedSource["postInstall"] = $$createField1_0($$parsedSource["postInstall"]);
        }
        return new RepoDTO(/** @type {Partial<RepoDTO>} */($$parsedSource));
    }
}

export class WorkspaceDTO {
    /**
     * Creates a new WorkspaceDTO instance.
     * @param {Partial<WorkspaceDTO>} [$$source = {}] - The source object to create the WorkspaceDTO.
     */
    constructor($$source = {}) {
        if (!("repos" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["repos"] = [];
        }
        if (!("lastUsed" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastUsed"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["postInstall"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repos" in $$parsedSource) {
            $$parsedSource["repos"] = $$createField0_0($$parsedSource["repos"]);
        }
        if ("postInstall" in $$parsedSource) {
            $$parsedSource["postInstall"] = $$createField2_0($$parsedSource["postInstall"]);
        }
        return new WorkspaceDTO(/** @type {Partial<WorkspaceDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = WorkspaceDTO.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Array($Create.Any);
