// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AIDTO {
    /**
     * Creates a new AIDTO instance.
     * @param {Partial<AIDTO>} [$$source = {}] - The source object to create the AIDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIDTO(/** @type {Partial<AIDTO>} */($$parsedSource));
    }
}

/**
 * ConfigDTO mirrors the HTTP layer's configResponse so the same React
 * types compile against either backend.
 */
export class ConfigDTO {
    /**
     * Creates a new ConfigDTO instance.
     * @param {Partial<ConfigDTO>} [$$source = {}] - The source object to create the ConfigDTO.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("editors" in $$source)) {
            /**
             * @member
             * @type {EditorDTO[]}
             */
            this["editors"] = [];
        }
        if (!("defaultEditor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultEditor"] = "";
        }
        if (!("ais" in $$source)) {
            /**
             * @member
             * @type {AIDTO[]}
             */
            this["ais"] = [];
        }
        if (!("defaultAI" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultAI"] = "";
        }
        if (!("workspaces" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: WorkspaceDTO }}
             */
            this["workspaces"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("editors" in $$parsedSource) {
            $$parsedSource["editors"] = $$createField1_0($$parsedSource["editors"]);
        }
        if ("ais" in $$parsedSource) {
            $$parsedSource["ais"] = $$createField3_0($$parsedSource["ais"]);
        }
        if ("workspaces" in $$parsedSource) {
            $$parsedSource["workspaces"] = $$createField5_0($$parsedSource["workspaces"]);
        }
        return new ConfigDTO(/** @type {Partial<ConfigDTO>} */($$parsedSource));
    }
}

/**
 * DetectedRepoDTO mirrors workspace.DetectedRepo for JSON. Match is the
 * repo name from the registry; "" when the dir didn't resolve.
 */
export class DetectedRepoDTO {
    /**
     * Creates a new DetectedRepoDTO instance.
     * @param {Partial<DetectedRepoDTO>} [$$source = {}] - The source object to create the DetectedRepoDTO.
     */
    constructor($$source = {}) {
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("remoteUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteUrl"] = "";
        }
        if (!("match" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["match"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedRepoDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectedRepoDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectedRepoDTO(/** @type {Partial<DetectedRepoDTO>} */($$parsedSource));
    }
}

export class EditorDTO {
    /**
     * Creates a new EditorDTO instance.
     * @param {Partial<EditorDTO>} [$$source = {}] - The source object to create the EditorDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EditorDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditorDTO(/** @type {Partial<EditorDTO>} */($$parsedSource));
    }
}

/**
 * OpenAICommandDTO is returned to JS so the UI can display + copy the AI
 * tool invocation — the app cannot exec a TTY program in place; it must
 * spawn a terminal (see OpenAI/OpenAIWith).
 */
export class OpenAICommandDTO {
    /**
     * Creates a new OpenAICommandDTO instance.
     * @param {Partial<OpenAICommandDTO>} [$$source = {}] - The source object to create the OpenAICommandDTO.
     */
    constructor($$source = {}) {
        if (!("ai" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ai"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAICommandDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenAICommandDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAICommandDTO(/** @type {Partial<OpenAICommandDTO>} */($$parsedSource));
    }
}

/**
 * OpenCommandDTO is returned to JS so the UI can display + copy the
 * editor invocation — the app cannot exec an editor that owns a TTY.
 */
export class OpenCommandDTO {
    /**
     * Creates a new OpenCommandDTO instance.
     * @param {Partial<OpenCommandDTO>} [$$source = {}] - The source object to create the OpenCommandDTO.
     */
    constructor($$source = {}) {
        if (!("editor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editor"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenCommandDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenCommandDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenCommandDTO(/** @type {Partial<OpenCommandDTO>} */($$parsedSource));
    }
}

/**
 * OrphanInspectionDTO is the response shape for InspectOrphan. Path is
 * the absolute on-disk path; Repos is the per-subdir detection result;
 * PreservedScripts are the workspace-scoped post-install scripts that
 * survived the prior remove and will be re-attached on Restore.
 */
export class OrphanInspectionDTO {
    /**
     * Creates a new OrphanInspectionDTO instance.
     * @param {Partial<OrphanInspectionDTO>} [$$source = {}] - The source object to create the OrphanInspectionDTO.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("repos" in $$source)) {
            /**
             * @member
             * @type {DetectedRepoDTO[]}
             */
            this["repos"] = [];
        }
        if (!("preservedScripts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["preservedScripts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrphanInspectionDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OrphanInspectionDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repos" in $$parsedSource) {
            $$parsedSource["repos"] = $$createField1_0($$parsedSource["repos"]);
        }
        if ("preservedScripts" in $$parsedSource) {
            $$parsedSource["preservedScripts"] = $$createField2_0($$parsedSource["preservedScripts"]);
        }
        return new OrphanInspectionDTO(/** @type {Partial<OrphanInspectionDTO>} */($$parsedSource));
    }
}

export class RepoDTO {
    /**
     * Creates a new RepoDTO instance.
     * @param {Partial<RepoDTO>} [$$source = {}] - The source object to create the RepoDTO.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["postInstall"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("postInstall" in $$parsedSource) {
            $$parsedSource["postInstall"] = $$createField1_0($$parsedSource["postInstall"]);
        }
        return new RepoDTO(/** @type {Partial<RepoDTO>} */($$parsedSource));
    }
}

export class WorkspaceDTO {
    /**
     * Creates a new WorkspaceDTO instance.
     * @param {Partial<WorkspaceDTO>} [$$source = {}] - The source object to create the WorkspaceDTO.
     */
    constructor($$source = {}) {
        if (!("repos" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["repos"] = [];
        }
        if (!("lastUsed" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastUsed"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["editor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["postInstall"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repos" in $$parsedSource) {
            $$parsedSource["repos"] = $$createField0_0($$parsedSource["repos"]);
        }
        if ("postInstall" in $$parsedSource) {
            $$parsedSource["postInstall"] = $$createField4_0($$parsedSource["postInstall"]);
        }
        return new WorkspaceDTO(/** @type {Partial<WorkspaceDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = EditorDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = AIDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = WorkspaceDTO.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = DetectedRepoDTO.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
